// Lesson content type definitions
// These interfaces define the structure of educational content
// that will be generated by the LLM and stored as JSONB in the database

/**
 * Quiz Question structure
 */
export interface QuizQuestion {
  id: string;
  question: string;
  options: [string, string, string, string]; // Exactly 4 options
  correctAnswer: 0 | 1 | 2 | 3; // Index of correct answer
  explanation?: string; // Why the answer is correct
  points?: number; // Points for this question (default: 10)
}

/**
 * Quiz content structure
 */
export interface QuizContent {
  questions: QuizQuestion[];
  totalPoints?: number;
  timeLimit?: number; // Time limit in seconds (optional)
  passingScore?: number; // Minimum score to pass (optional)
}

/**
 * Tutorial Section structure
 */
export interface TutorialSection {
  id: string;
  title: string;
  content: string; // Markdown content
  examples?: Array<{
    language?: string; // Programming language for syntax highlighting
    code: string; // Code example
    explanation?: string; // What the code does
  }>;
  order: number; // Section ordering
}

/**
 * Tutorial content structure
 */
export interface TutorialContent {
  sections: TutorialSection[];
  estimatedReadTime?: number; // Minutes
  difficulty?: "beginner" | "intermediate" | "advanced";
  prerequisites?: string[]; // Topics to know beforehand
}

/**
 * Flashcard structure
 */
export interface Flashcard {
  id: string;
  front: string; // Question or term
  back: string; // Answer or definition
  category?: string; // Optional grouping
  difficulty?: "easy" | "medium" | "hard";
}

/**
 * Flashcard content structure
 */
export interface FlashcardContent {
  cards: Flashcard[];
  totalCards: number;
  categories?: string[]; // List of unique categories
}

/**
 * Visualization content structure (future)
 */
export interface VisualizationContent {
  type: "chart" | "graph" | "timeline";
  data: Record<string, unknown>; // Flexible data structure
  config?: Record<string, unknown>; // Visualization config
}

/**
 * Diagram content structure (future)
 */
export interface DiagramContent {
  nodes: Array<{
    id: string;
    label: string;
    type?: string;
    data?: Record<string, unknown>;
  }>;
  edges: Array<{
    id: string;
    source: string;
    target: string;
    label?: string;
  }>;
  layout?: "horizontal" | "vertical" | "radial";
}

/**
 * Union type for all lesson content types
 */
export type LessonContent =
  | { type: "quiz"; data: QuizContent }
  | { type: "tutorial"; data: TutorialContent }
  | { type: "flashcard"; data: FlashcardContent }
  | { type: "visualization"; data: VisualizationContent }
  | { type: "diagram"; data: DiagramContent };

/**
 * Lesson status
 */
export type LessonStatus = "generating" | "generated" | "failed";

/**
 * Lesson type
 */
export type LessonType = "quiz" | "tutorial" | "flashcard" | "visualization" | "diagram";

/**
 * Complete lesson structure (matches DB schema)
 */
export interface Lesson {
  id: string;
  userId: string;
  title: string;
  outline: string;
  description?: string;
  status: LessonStatus;
  content?: LessonContent;
  researchNotes?: string[];
  lessonType?: LessonType;
  errorMessage?: string;
  createdAt: Date;
  updatedAt: Date;
}
